#!/usr/bin/bash

# get ngrok url and create env var
ADDR=$(curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"https:..([^"]*).*/\1/p')
TELEGRAM_WEBHOOK="https://${ADDR}"
export TELEGRAM_WEBHOOK
